### PR TITLE
Multi image GTX files can now be created from DDS ; full support for exporting/importing Mipmaps

### PR DESCRIPTION
**Pull request by dragonbane0**
This is quite a substantial addition that adds support to re-import multiple DDS files into one big GTX file. Furthermore if the command line -mips is added at the end all the Mipmaps will be exported to the respective DDS files as well when converting from GTX. If converting from DDS to GTX the same command will also re-import all the Mipmaps automatically. Otherwise numMips will be set to 1 as usual

I could only test TP HD so I can't say if this code has full compatibility. TP HD uses multi image GTX files and the engine also relies on the mipmaps being present or the textures will show up garbled with only 1 mipmap in the file. At least all the textures I tried could be perfectly exported and re-imported too including the mipmaps!

My little creative change to the Title Screen logo. It uses 8 images in one GTX file each having up to 11 Mipmaps: 

Example

This now makes modding textures possible across many games. Feel free to suggest additions and changes. I would really appreciate if you could add me under Credits if you decide to pull this :)

PS: I also updated the GIMP DDS Plugin to support the L4A4 format for importing/exporting since I couldn't find any other tool that supports it properly: https://github.com/dragonbane0/gimp-dds

### CODE REVIEW

**Comment by aboood40091** [comment]
Nice, I'll do some more tests before merging. ;)

**Comment by aboood40091** [comment]
But, hey, isn't LA4 already supported... ?

**Comment by dragonbane0** [comment]
The old GIMP DDS Plugin could read L4A4 due the way it is written, but not really accurately (it lumps alpha and luminance together). Export was missing altogether. The best it supported was L8A8. Unless I missed the latest version of the plugin, it was originally on Google code so Im not sure

GTX-Extractor supports L4A4 of course, just GIMP wasnt so you couldnt edit it well

**Comment by dragonbane0** [comment]
As far as I could see L4A4 was the only thing missing from GIMP. All the other formats GTX-Extractor supports GIMP can both import and export perfectly so full modding for all of those formats should be possible now

**Comment by aboood40091** [comment]
Umm, I have two comments.

1. Gimp doesn't support BGR565 and a few other formats.
2. The first mipmap doesn't get deswizzled correctly.

**Comment by aboood40091** [comment]
I fixed the mipmaps thing.

**Comment by aboood40091** [comment]
Maybe you could contribute to this one too? 😄
https://github.com/aboood40091/RandomStuff/blob/master/gtx_extract.c

**Comment by aboood40091** [comment]
TODO: Generate mipmaps.
I don't think that would be hard.

**Comment by dragonbane0** [comment]
Well GIMP supports RGB565 at least. Flipping R and B should be easy to add. I guess I will do that

**Comment by dragonbane0** [comment]
Good fix on the mipmap, I didnt catch that. I wanted to leave mipmaps to the user because swizzling can take quite a while so if a file has 11 mipmaps it can take ages to export/import. But its probably for the best to not export them since they dont really matter for editing. On import we can check if there are mipmaps in the dds file and if so import them

**Comment by aboood40091** [comment]
"Well GIMP supports RGB565 at least. Flipping R and B should be easy to add. I guess I will do that"
Here are the unsupported formats that I know:
* BGR565
* BGR5A1
* BGRA4

**Comment by dragonbane0** [comment]
Mhm since your change to the pitch the mipmaps dont show up correctly anymore for my TP HD textures. I assume the way I calculate the pitch might be correct for some textures, while your way is correct for others. 

Here is an example file that has correct mipmaps with the pitch being calculated as:   
`mipPitch = 2**(surface.numMips - 1 - index)`

good

With your fix it shows up as this:
bad

Here is the file for testing:
[titlelogo_r.bmd.zip](https://github.com/aboood40091/GTX-Extractor/files/1050386/titlelogo_r.bmd.zip)

**Comment by aboood40091** [comment]
Don't worry, I fixed the problem.
I'll push my changes soon.

**Comment by aboood40091** [comment]
Hi, sorry for not commenting for a while. 😅

I just want to tell you that I have moved your changes to another branch and that I've rewritten lots of things.
I've finally got pitch calculation working, and lots of things too.

I've just rewritten mipmaps extracting from scratch and it worked with your textures and my textures! 😄

I'll now rewrite creating GTX files from multiple images.

**Comment by dragonbane0** [comment]
awesome!! Im gonna check it out :D

**Comment by aboood40091** [comment]
Wow, took you a while to respond. 😂
Anyway, I have rewritten everything and everything works now.

**Comment by aboood40091** [comment]
Oh, I also speed up the swizzling (by rewritting the swizzle code in Cython), so, you don't have to worry about how much time mipmaps extracting will take. 😅

**Comment by aboood40091** [comment]
So, about BGR565, BGRA4, and BGR5A1, you could forget about those.
What I want you to add is BGR10A2. Gimp supports viewing it, but can only export RGB10A2.

BGR10A2 is important for BFLIM, so, I wondered if you could add exporting as this format. ^-^

**Comment by aboood40091** [comment]
GTX has something called Component Selectors (compSel for short), which are kinda similar to the RGBA masks in DDS.
So, it doesn't really matter if R and B are swapped since we can use compSel to indicate that R and B are swapped.

BFLIM doesn't have compSel, so, it would be a problem if R and B are swapped, and, you guessed it, RGB10A2 is a problem here.

**Comment by moonshinealkaline** [comment]
I'm sorry if I overlooked a simple solution to this but how do I import multiple DDS files into a single GTX file. When I select all the files and then drag and drop them to "gtx_extract.exe", the program only packs one of the DDS files into the GTX file for me.

**Comment by aboood40091** [comment]
While I do feel bad about bumping such an old pull request, I wanted to say that I actually went ahead and started a rewrite of the tool that should basically handle all of this in a new way.
You can find the progress [here](https://github.com/aboood40091/GTX-Extractor-Rewrite).

As of now, it can batch extract textures (including mipmaps) in GTX files to png files with correct color and all.
For example, here are the textures extracted from the GTX file you sent:
[titlelogo_r.bmd.zip](https://github.com/aboood40091/GTX-Extractor/files/5137927/titlelogo_r.bmd.zip)

I am still working on the new DDS writer.

**Pull request merged**
